### ISSUE TITLE
Virtual Makeup Demo?

### ISSUE THREAD

**Issue by longerking** [Pavankunchala/Streamlit-Applications#1]
Hello, I am very interested in virtual makeup in your project, but I did not find any code to describe it in the project.

[Virtual Makeup](https://share.streamlit.io/pavankunchala/virtual_makeup_streamlit/main/app.py)

I want to talk to you and learn about virtual makeup, Is it based on mediapipe?

If you want, can you open source part of the code or give me a little help?   My mail address is longerking@fixmail.com

**Comment by Pavankunchala** [comment]
Mailed you regarding the same

**Comment by longerking** [comment]
> Mailed you regarding the same

Sorry, the above email is wrong, the correct email is longerking@foxmail.com, can you resend the email again?   Thanks! 😄
